# Generated by Django 5.2.7 on 2025-10-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="required_dlcs",
            field=models.JSONField(blank=True, db_column="requiredDLCs", default=list),
        ),
        migrations.AlterField(
            model_name="missionslot",
            name="required_dlcs",
            field=models.JSONField(blank=True, db_column="requiredDLCs", default=list),
        ),
    ]
