"""
Django settings for slotlist_backend project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-09agi7ja8ofs3rtlpfi@6jpgkpbd#ed&2&-uvfyc%@fsm)n%-h')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition
# These will be overridden below based on environment

ROOT_URLCONF = 'slotlist_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'slotlist_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Detect if running in Cloudflare Workers environment
def is_cloudflare_workers():
    # Primary detection: explicit environment variable
    use_d1 = os.getenv('USE_D1_DATABASE', '').lower() in ('true', '1', 'yes')
    if use_d1:
        return True
    
    # Secondary detection: check for Workers-specific environment
    try:
        # Check for Cloudflare Workers runtime characteristics
        import sys
        if 'pyodide' in sys.modules or hasattr(__builtins__, 'addEventListener'):
            return True
    except:
        pass
    
    return False

if is_cloudflare_workers():
    # Use D1 database binding for Cloudflare Workers
    DATABASES = {
        'default': {
            'ENGINE': 'django_cf.d1_binding',
            'CLOUDFLARE_BINDING': 'DB',  # Must match binding name in wrangler.toml
        }
    }
    
    # Minimal configuration for Cloudflare Workers to avoid conflicts
    # Remove problematic apps that aren't needed for API-only deployment
    INSTALLED_APPS = [
        'django.contrib.contenttypes',
        'django.contrib.auth',
        'corsheaders',
        'django_cf',
        'api',
    ]
    
    # Minimal middleware for Workers
    MIDDLEWARE = [
        'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
    ]
    
    # Disable features that can cause startup conflicts in Workers
    USE_I18N = False
    USE_L10N = False
    USE_TZ = True  # Keep timezone support for API
    
    # Disable static files handling for Workers
    STATIC_URL = None
    STATIC_ROOT = None
    STATICFILES_DIRS = []
    
    # Minimal password validation for Workers
    AUTH_PASSWORD_VALIDATORS = []
    
    # Disable admin interface completely
    ADMIN_ENABLED = False
    
else:
    # Use PostgreSQL for local development and traditional deployments
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_DATABASE', 'slotlist'),
            'USER': os.getenv('DB_USERNAME', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
    
    # Full configuration for local development
    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'corsheaders',
        'django_cf',
        'api',
    ]

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'corsheaders.middleware.CorsMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'
CORS_ALLOW_CREDENTIALS = True

# Always allow localhost and Docker service names for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:4000", 
    "http://127.0.0.1:3000",
    "http://127.0.0.1:4000",
    "http://frontend-dev:3000",
    "http://frontend:4000",
    "http://backend:8000",
]

# Also allow localhost and Docker network patterns for any port
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
    r"^http://frontend-dev:\d+$",
    r"^http://frontend:\d+$",
    r"^http://backend:\d+$",
]

# Allow specific headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# JWT Settings
JWT_SECRET = os.getenv('CONFIG_JWT_SECRET', 'change-me-in-production')
JWT_ALGORITHM = 'HS256'
JWT_ISSUER = os.getenv('CONFIG_JWT_ISSUER', 'slotlist.info')
JWT_AUDIENCE = os.getenv('CONFIG_JWT_AUDIENCE', 'slotlist.info')
# 24 hours in seconds (default)
try:
    JWT_EXPIRES_IN = int(os.getenv('CONFIG_JWT_EXPIRESIN', '86400'))
except (ValueError, TypeError):
    JWT_EXPIRES_IN = 86400

# Steam API
STEAM_API_SECRET = os.getenv('CONFIG_STEAM_API_SECRET', '')

# Google Cloud Storage
GCS_BUCKET_NAME = os.getenv('CONFIG_STORAGE_BUCKETNAME', '')
GCS_PROJECT_ID = os.getenv('CONFIG_STORAGE_PROJECTID', '')

# Default Admin User
DEFAULT_ADMIN_UID = os.getenv('DEFAULT_ADMIN_UID', None)
DEFAULT_ADMIN_STEAMID = os.getenv('DEFAULT_ADMIN_STEAMID', '')
DEFAULT_ADMIN_NICKNAME = os.getenv('DEFAULT_ADMIN_NICKNAME', '')

# Sentry DSN
SENTRY_DSN = os.getenv('SENTRY_DSN', '')

# Security Headers
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

